-- AlterTable
ALTER TABLE "Conversation" ADD COLUMN     "user1_last_read_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "user2_last_read_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
